# Generated by Django 4.1.7 on 2023-02-24 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=8)),
                ('categoria', models.CharField(max_length=1)),
                ('preco_diaria', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.marca')),
            ],
        ),
    ]
