# Generated by Django 4.1.7 on 2023-02-24 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('data_pagamento', models.DateTimeField()),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserva_pagamento', to='cliente.reserva')),
            ],
        ),
    ]
